name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "news_now"
database_id = "c2b04846-7282-4d80-a9a9-130fcf67452c"
